---
- name: Installer Apache et vérifier son statut
  hosts: my_servers
  become: true
  tasks:
    - name: Installer Apache
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true

    - name: Vérifier que le service Apache est en cours d'exécution
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

    - name: Copier le fichier desktop.ini depuis l'ordinateur local
      ansible.builtin.copy:
        src: /root/ansible/exo2/playbook_apache.yml
        dest: /desktop.ini
        owner: root
        group: root
        mode: "0644"

    - name: Modifier les permissions du fichier
      ansible.builtin.file:
        path: /desktop.ini
        mode: "0755"
