---
- name: Installer Apache sur plusieurs hôtes
  hosts: "my_servers"
  become: true
  tasks:
    - name: Installer Apache
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true
