---
- name: Check uname command on remote host
  hosts: my_servers
  vars:
    report_path: ./report/script_report.txt
    permissions: "0600"
  tasks:
    - name: Execute uname -a
      ansible.builtin.command: uname -a
      register: uname_output
      changed_when: uname_output.rc != 0

    - name: Enregistrer la sortie dans un fichier sur la machine locale
      ansible.builtin.copy:
        content: "{{ uname_output.stdout }}"
        dest: "{{ report_path }}"
        mode: "{{ permissions }}"
      delegate_to: localhost
