---
- name: Verifie la commande uname
  hosts: my_servers
  tasks:
    - name: Execute uname -a
      ansible.builtin.command: uname -a
      register: uname_output
      changed_when: uname_output.rc != 0

    - name: Affiche le résultat uname
      ansible.builtin.debug:
        var: uname_output.stdout
